### ISSUE TITLE
Couldn't load module library?

### ISSUE THREAD

**Issue by grande1900** [devonium/EGSM#1]
I placed the `gmsv_egsm_win32.dll` into the `garrysmod\lua\bin\` folder and added `require("egsm")` to `garrysmod\lua\menu\menu.lua`, but I keep getting this error:
```
[MENU ERROR] lua/menu/menu.lua:19: Couldn't load module library! (The specified procedure could not be found.)
  1. require - [C]:-1
   2. unknown - lua/menu/menu.lua:19
    3. include - [C]:-1
     4. unknown - lua/includes/menu.lua:9
```
I'm running x86-x64 on 32-bit, (for compatibility) and with `-noaddons -noworkshop`.

**Comment by meetric1** [comment]
You need to be on the `Main` branch for this to work, `x64-x86` doesn’t for whatever reason.

hopefully he adds compatibility in the future

**Comment by ttmso** [comment]
uhhhhh, the game now crashs when i start it, not when i join a map, but when: serverside loading, maybe this is a problem:
![image](https://user-images.githubusercontent.com/93525030/223093088-2f7fbfd8-90dc-4b6b-a765-424a89ef5b64.png)

**Comment by ttmso** [comment]
ok its not the problem but here is a video
https://user-images.githubusercontent.com/93525030/223093789-6040bed9-04df-4e57-bcff-b2ffdf501e7b.mp4

**Comment by ttmso** [comment]
menu.lua:
![image](https://user-images.githubusercontent.com/93525030/223094451-ad90971f-43af-43f3-860e-5a7b02ad9c87.png)

**Comment by devonium** [comment]
Try to reinstall gmod

**Comment by ttmso** [comment]
hmmm ok

**Comment by ttmso** [comment]
still doesn't work
