### ISSUE TITLE
Pixel Shader Ambient cube

### ISSUE THREAD

**Issue by Goldermor** [devonium/EGSM#10]
STDCONST_AMBIENT_CUBE doing nothing for Pixel shader,
instead, it somehow fixes blinking for ambient cube in vertex shader.

so it's impossible to have pixel shader ambient cube for now.

**Comment by devonium** [comment]
idk, [this](https://github.com/devonium/EGSM/wiki/example_shaders#basic-lightning--lack-of-vertex-position-precision-per-object) seems to work without any change
Could you tell me your branch and how do you use STDCONST_AMBIENT_CUBE?

**Comment by Goldermor** [comment]
even in your example it doesn't work, check it yourself

**Comment by Goldermor** [comment]
it may seem like it works, but if you put it in the shadow, it will be completely black

**Comment by devonium** [comment]
uh oh i thought It was supposed to work that way
