### ISSUE TITLE
cant start gmod with bin and menu file

### ISSUE THREAD

**Issue by ttmso** [devonium/EGSM#3]
https://user-images.githubusercontent.com/93525030/223451109-09a1dd29-f8fd-42b9-8f68-2faee51eceb2.mp4

**Comment by devonium** [comment]
Try running gmod with Dependency Walker, maybe your pc is missing some dlls

**Comment by ttmso** [comment]
oh, v1.1 fixed it lol

**Comment by devonium** [comment]
hm okay
