### ISSUE TITLE
where do i put the lua file

### ISSUE THREAD

**Issue by ttmso** [devonium/EGSM#5]
so i made the vmt but idk where to put the lua file, in autorun/client?

**Comment by ttmso** [comment]
yeah
![image](https://user-images.githubusercontent.com/93525030/223703582-f88f6506-15a6-4be5-b569-8928c36288a6.png)
![image](https://user-images.githubusercontent.com/93525030/223703641-7f14cb6f-fdc3-4c49-9a5c-f4cfdfa40155.png)

**Comment by ttmso** [comment]
i have both the menu.lua thing and the bin file

**Comment by ttmso** [comment]
oh shit, im a idiot
![image](https://user-images.githubusercontent.com/93525030/223704013-516d6766-867e-4446-857f-da4b095ec2a5.png)

**Comment by ttmso** [comment]
oh no, oh no not you again
https://user-images.githubusercontent.com/93525030/223705010-045626dd-23b7-4397-b5ae-9dfbe0de4c34.mp4

**Comment by ttmso** [comment]
so i got rid of all the addons and checked the verify integrity of game files, and still doesn't work...

**Comment by devonium** [comment]
i don't have a way to reproduce, so i've no idea what could cause it

**Comment by ttmso** [comment]
ok ):

**Comment by ttmso** [comment]
so i factory reset gmod and now it works (:
and i made this:
![image](https://user-images.githubusercontent.com/93525030/229092252-354a9925-959f-4fcb-99ce-c796eb303f22.png)

**Comment by ttmso** [comment]
i just copied the soble shader and then changed some shit and boom, code:

shaderlib.CompileVertexShader("SobelOperatorVertexShader", 0, [==[
#include "common_vs_fxc.h"

struct VS_INPUT
{
	float4 vPos					: POSITION;
};

struct VS_OUTPUT
{
	float4 projPosSetup	: POSITION;
};

VS_OUTPUT main( const VS_INPUT v )
{
	VS_OUTPUT o = (VS_OUTPUT)0;

	float4 vProjPos = mul(  v.vPos, cViewProj );
	vProjPos.z = dot( v.vPos, cViewProjZ );
  	o.projPosSetup = vProjPos;
	return o;
}

]==])

shaderlib.CompilePixelShader("SobelOperatorPixelShader", 0, [==[

sampler FrameBuffer : register(s0);
float3  SBColor : register(c0);

struct PS_IN
{
	float2 P 			: VPOS;
};

float4 main(PS_IN i ) : COLOR
{
    float4 pixel = tex2D(FrameBuffer, i.P/float2(1920, 1080));
    // float4 pixel = PARAM_COLOR

	// float4 color = pixel/sin(i.P.x/100);
    float4 color = float4(1-pixel.x, 1-pixel.y, 1-pixel.z, 1);

	return color;
};

]==])

**Comment by ttmso** [comment]
also im wondering if you can make it so a time var is in it, i want to make a procedural pulse effect

**Comment by ttmso** [comment]
also the sun is a black hole wtf
![image](https://user-images.githubusercontent.com/93525030/229093160-1eabbc8d-48b9-4128-bc0e-ea891c3404c8.png)

**Comment by ttmso** [comment]
lol *villager hmmm*
![image](https://user-images.githubusercontent.com/93525030/229101971-f2568ccf-8346-47ce-aa7c-69ee85ca4215.png)

**Comment by ttmso** [comment]
code:
```hlsl
if !EGSM or !(EGSM.Version > 0) then return end -- DON'T FORGET TO CHECK
local function CompileShaders()
shaderlib.CompileVertexShader("SobelOperatorVertexShader", 0, [==[
#include "common_vs_fxc.h"

struct VS_INPUT
{
	float4 vPos					: POSITION;
};

struct VS_OUTPUT
{
	float4 projPosSetup	: POSITION;
};

VS_OUTPUT main( const VS_INPUT v )
{
	VS_OUTPUT o = (VS_OUTPUT)0;

	float4 vProjPos = mul(  v.vPos, cViewProj );
	vProjPos.z = dot( v.vPos, cViewProjZ );
  	o.projPosSetup = vProjPos;
	return o;
}

]==])

shaderlib.CompilePixelShader("SobelOperatorPixelShader", 0, [==[

sampler FrameBuffer : register(s0);
float3  SBColor : register(c0);

struct PS_IN
{
	float2 P 			: VPOS;
};

float4 main(PS_IN i ) : COLOR
{
    float4 pixel = tex2D(FrameBuffer, (i.P+float2(sin((i.P.x/16))*16, sin((i.P.y/16))*16))/float2(SCR_W, SCR_H));

    float4 color = pixel/float4(1, 1.25, 1.25, 1);

	return color;
};

]==])

end
CompileShaders()

local shader = shaderlib.NewShader("SobelOperator")

shader:SetPixelShader("SobelOperatorPixelShader")
shader:SetVertexShader("SobelOperatorVertexShader")

shader:BindTexture(0, PARAM_BASETEXTURE)

local SBColor = shader:AddParam("$SBColor", SHADER_PARAM_TYPE_COLOR)
shader:SetPixelShaderConstantFP(0, SBColor)

local mat = Material("lucman/test_shader")
local screentexture = render.GetScreenEffectTexture()

hook.Add("RenderScreenspaceEffects", "SobelOperator", function()
	render.UpdateScreenEffectTexture()
	render.CopyRenderTargetToTexture(screentexture)
	render.SetMaterial(mat)
	render.DrawScreenQuad()
end )

hook.Add("RecompileShaders", shader:GetName(), CompileShaders)
```

**Comment by ttmso** [comment]
omg steve is dead
![image](https://user-images.githubusercontent.com/93525030/229102472-537c85cf-8d99-46d0-a68a-c9cd4fb7fde2.png)

**Comment by devonium** [comment]
> also im wondering if you can make it so a time var is in it, i want to make a procedural pulse effect
```lua
shader:SetPixelShaderStandardConstant(index, STDCONST_CURTIME)
```

**Comment by ttmso** [comment]
nice

**Comment by ttmso** [comment]
is there a depth buffer too?

**Comment by ttmso** [comment]
oh good idea: make a discord server where people can show what they made and ask how to do things like me

**Comment by devonium** [comment]
> is there a depth buffer too?

_rt_ResolvedFullFrameDepth


> oh good idea: make a discord server where people can show what they made and ask how to do things like me

https://discord.gg/X2Ay3cgW8T
