### ISSUE TITLE
Possible to sample the entity's $color2?

### ISSUE THREAD

**Issue by ZH-Hristov** [devonium/EGSM#6]
Just trying to modify the sobel operator shader to sample it's color from the one set by the color tool. I'm new to this HLSL stuff but it seems fun to play around with.

**Comment by ttmso** [comment]
i dont know of any way to do that but maybe devon knows

**Comment by devonium** [comment]
```
SetPixelShaderConstantFP(0, PARAM_COLOR2)
```

**Comment by ZH-Hristov** [comment]
> ```
> SetPixelShaderConstantFP(0, PARAM_COLOR2)
> ```

Tried this but it doesn't seem to work, at least when editing the per object sobel operator shader. Coloring the ent with the tool didn't change anything, whether the constant was set to the SBColor param or a different one.

**Comment by devonium** [comment]
The color tool doesn't set $COLOR2
To get the color of entity, use
```lua
SetPixelShaderStandardConstant(PSREG_DIFFUSE_MODULATION, STDCONST_DIFFUSE_MODULATION)
```

**Comment by devonium** [comment]
You also need to include `shader_constant_register_map.h` so you can use PSREG_DIFFUSE_MODULATION in your shader code

**Comment by ZH-Hristov** [comment]
Thanks! That works great!


https://user-images.githubusercontent.com/7620140/223880408-233464e8-1b6a-4538-be78-7b7813afbba2.mp4
