### ISSUE TITLE
Advanced DepthBuffer 

### ISSUE THREAD

**Issue by Goldermor** [devonium/EGSM#7]
Current DepthBuffer really limited. And I'm not talking about the range, actually, you did a good job with it. I'm talking about selective depth. like, being able to get multiple depth buffers, for example, world only DepthBuffer. Because now, DepthBuffer takes into account some effects and in general it breaks visual on C_BaseAnimating entities when it is called to render.
![depth_1](https://user-images.githubusercontent.com/77431249/227571373-18dfef31-b6da-4fa3-af10-7c6ba95092b1.png)
![depth_3](https://user-images.githubusercontent.com/77431249/227578995-2f1a2834-1521-44c5-9ecf-bcd9d3f99fd0.png)

it's not just the depth, effects appear on top of it
![depth_4](https://user-images.githubusercontent.com/77431249/227581878-96be09e7-cebb-4613-909d-a8233e5eeb42.png)

![depth_2](https://user-images.githubusercontent.com/77431249/227571944-0c1ca842-0529-401d-bc2e-54d216da06c0.png)
![depth3](https://user-images.githubusercontent.com/77431249/227572327-51aeb972-ff2e-4fae-b675-0e48fc30c08a.png)
invisibility can be fixed with DOFModeHack(true) but its just hack :/

Of course, the biggest problem is that transparent effects get into the depth image for some reason and it's worth fixing primarily, the other request is not so important.

**Comment by meetric1** [comment]
I was able to fix the npc bug by doing `pp_bokeh "` which fixed it for some reason

**Comment by devonium** [comment]
So got the depth buffer issue fixed, but the invisibility issue, I guess you just could use the DOFModeHack, it seems to work perfect, so why bother.
